-- stolen from https://github.com/KevinPalowa/nvim/

require("nanasss.options")
require("nanasss.autocmds")
require("nanasss.keymaps")
require("nanasss.plugins")
require("nanasss.colorscheme")
require("nanasss.cmp")
require("nanasss.lsp")
require("nanasss.telescope")
require("nanasss.presence")
require("nanasss.toggleterm")
require("nanasss.lualine")
require("nanasss.autopairs")
require("nanasss.comment")
require("nanasss.gitsigns")
require("nanasss.nvimtree")
require("nanasss.treesitter")
require("nanasss.bufferline")
require("nanasss.indentline")
require("nanasss.trouble")
require("nanasss.alpha")
require("nanasss.project")
require("nanasss.colorizer")
require("nanasss.whichkey")
